# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 01:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garden', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Garden')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPalIPN'), ('cash', 'Cash/Check'), ('adjustment', 'Adjustment (gift from garden)'), ('refund', 'Refund'), ('legacy', 'Legacy')], max_length=32)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('canceled', models.DateField(blank=True, null=True)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='If zero, this membership will always be active until deleted.', max_digits=30)),
                ('owed', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('subscr_id', models.CharField(blank=True, help_text='Only used with PayPal subscriptions. Do not touch.', max_length=20, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Membership')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Plot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
