# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Membership'),
        ),
    ]
