# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180513_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gardenbuddy',
            options={'verbose_name': 'garden buddy', 'verbose_name_plural': 'garden buddies'},
        ),
        migrations.AlterUniqueTogether(
            name='gardenbuddy',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='gardenbuddy',
            name='garden_buddy',
        ),
    ]
