# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180513_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_garden_buddy',
            field=models.BooleanField(default=False),
        ),
    ]
