# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180508_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='uuid',
            field=models.CharField(default=user.models.get_uuid, editable=False, max_length=32),
        ),
    ]
