# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='chair',
            field=models.ManyToManyField(blank=True, related_name='chair', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
