# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180513_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemembership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
